nadine_coiffure_front_home:
    path:      /
    defaults:  { _controller: NadineCoiffureBundle:Front/Default:index }

nadine_coiffure_front_services:
    path:      /services
    defaults:  { _controller: NadineCoiffureBundle:Front/Default:services }

nadine_coiffure_front_contact:
    path:      /contact
    defaults:  { _controller: NadineCoiffureBundle:Front/Default:contact }
